### ISSUE TITLE
'CUDA_ERROR_UNKNOWN' error using DeepVariant GPU version.

### ISSUE THREAD

**Issue by sen1019san** [google/deepvariant#619]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**: Yes

**Describe the issue:**
'CUDA_ERROR_UNKNOWN' using DeepVariant GPU version.

**Setup**
  - Operating system: CentOS Linux release 7.4.1708 (Core), Linux 5.10.150-1.el7.x86_64
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): singularity image build from dockerhub
  - Type of data: nothing special that is unlike the case studies

**Steps to reproduce:**
  - Command:  /opt/deepvariant/bin/run_deepvariant --version
  - Error trace: (if applicable)
 ```
tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 
tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 
tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: INVALID_ARGUMENT: expected %d.%d, %d.%d.%d, or %d.%d.%d.%d form for driver version; got "1"
tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 520.61.5
DeepVariant version 1.4.0
```
The `hostname` is privacy.

**Does the quick start test work on your system?:** No

**Any additional context:** 
The GPU is NVIDIA GeForce 3090
The GPU Driver Version: 520.61.05
The CUDA version in the host is V11.8.89 as followings:
![image](https://user-images.githubusercontent.com/43125963/225341539-aa2ee3c6-c376-4758-a582-c8fd871b0508.png)
It seems that the Deepvariant v1.4.0 in the singularity image has already installed CUDA v11.3. 
![image](https://user-images.githubusercontent.com/43125963/225343337-d0924a9b-4b9d-4b03-848f-e8e9753eb377.png)

I don't know whether it causes the program crash.

**Comment by pichuan** [comment]
Hi @sen1019san 
You mentioned you're using singularity image build from dockerhub, and you're using the GPU version.
1. Just to make sure we can reproduce the steps, can you given an en example of the command you ran?
2. We have 1.5.0 as well. Does that work for you, or does that also crash?

**Comment by sen1019san** [comment]
Hi, @pichuan, thanks for your quick replay.
I ran the command `/opt/deepvariant/bin/run_deepvariant --version` using GPU version in singularity image .  It return the `CUDA_ERROR_UNKNOWN` error as above I mentioned.

Now I am trying to use the 1.5.0 version.

**Comment by pichuan** [comment]
Can you share the command you ran roght before you got into the place where you ran the command?
Thanks.

**Comment by pichuan** [comment]
Do you have CUDA installed on your machine?

Check whether CUDA is installed on your machine. For example, run:
```
rpm -qa | grep cuda
```
or
```
nvcc --version
```

If you don't have CUDA installed, please follow the instructions on https://docs.nvidia.com/cuda/cuda-installation-guide-linux/ to make sure you install it.

**Comment by sen1019san** [comment]
Hi, @pichuan.
I am sure the CUDA is installed on the host. The CUDA version is V11.8.89.
![image](https://user-images.githubusercontent.com/43125963/225511464-62c75283-b925-4b19-aea4-a75913ffd224.png)

**Comment by pichuan** [comment]
I see. Right you mentioned that before.
It could be that the versions are different. Let me see if it's possible for me to get a CentOS7 set up with CUDA version V11.8.89 and then test with that.

**Comment by sen1019san** [comment]
Hi, @pichuan. Thanks for your quick reply. I wish the problem to be solved quickly.

**Comment by pichuan** [comment]
I got a machine to test:

```
gcloud compute instances create "${USER}-gpu" \
  --scopes "compute-rw,storage-full,cloud-platform" \
  --maintenance-policy "TERMINATE" \
  --accelerator=type=nvidia-tesla-p100,count=1 \
--image-family "centos-7" \
--image-project "centos-cloud" \
  --machine-type "n1-standard-16" \
  --boot-disk-size "300" \
  --zone "us-west1-b" \
  --min-cpu-platform "Intel Skylake"
```

On the machine, I install nvidia driver first:

```
sudo yum update -y && sudo yum install -y python3
curl https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py --output install_gpu_driver.py
sudo python3 install_gpu_driver.py
```

After that, I can confirm that nvidia-smi exists:
```
[pichuan@pichuan-gpu2 ~]$ nvidia-smi
Thu Mar 16 04:47:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    29W / 250W |      0MiB / 16384MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Then I install cuda. This was from: https://developer.nvidia.com/cuda-downloads
```
curl -O https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_530.30.02_linux.run 
export TERM=xterm
sudo sh cuda_12.1.0_530.30.02_linux.run
```

```
export PATH=/usr/local/cuda-12.1/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64:$LD_LIBRARY_PATH
sudo ldconfig
```

```
[pichuan@pichuan-gpu2 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

This is not 11.8, but is a newer version. So let's test with it.

Install Singularity:

```
curl -O https://raw.githubusercontent.com/google/deepvariant/r1.5/scripts/install_singularity.sh
sed -i -e 's/apt-get/yum/g' install_singularity.sh
bash -x install_singularity.sh
```

Check version:
```
[pichuan@pichuan-gpu2 ~]$ singularity --version
singularity version 3.7.0
```

The rest is similar to https://github.com/google/deepvariant/issues/514#issuecomment-1035630725 , but with v1.5.0.

```
# Pull the image.
BIN_VERSION=1.5.0
singularity pull docker://google/deepvariant:"${BIN_VERSION}-gpu"

# Run DeepVariant.
# Using "--nv" and "${BIN_VERSION}-gpu" is important.
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:"${BIN_VERSION}-gpu" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=$(nproc)
```
That worked.

I can use this setup to try the way you run it as well. I'll report back later.

**Comment by pichuan** [comment]
Actually, when I took a closer look at the logs, it says:

```
2023-03-16 05:35:30.141288: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-03-16 05:35:30.141355: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: pichuan-gpu2
2023-03-16 05:35:30.141366: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: pichuan-gpu2
2023-03-16 05:35:30.141423: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: INVALID_ARGUMENT: expected %d.%d, %d.%d.%d, or %d.%d.%d.%d form for driver version; got "1"
2023-03-16 05:35:30.141471: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 530.30.2
```

So it seems like I'm able to reproduce this issue. 

Let me take a closer look. I'll also want to test this on Ubuntu. I tested before release, but I'll want to test it again.

**Comment by pichuan** [comment]
I ran:

```
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/   docker://google/deepvariant:"${BIN_VERSION}-gpu"   python -c 'import tensorflow as tf;print(tf.test.is_gpu_available())'
```
This printed False, which confirmed that this setup was indeed not seeing GPU.  :(

Let me test on Ubuntu to get another data point.

**Comment by sen1019san** [comment]
Hi, @pichuan. Thanks a lot for your quick reply and for trying.

**Comment by pichuan** [comment]
I'm going to try installing CUDA 11.3 on the CentOS7 machine first, to confirm whether that will address the issue.

I followed: https://developer.nvidia.com/cuda-11.3.0-download-archive?target_os=Linux

```
wget https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda_11.3.0_465.19.01_linux.run
sudo sh cuda_11.3.0_465.19.01_linux.run
```

```
export PATH=/usr/local/cuda-11.3/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH
sudo ldconfig
```

```
[pichuan@pichuan-gpu2 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

Now, with this, I tried:

```
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/   docker://google/deepvariant:"${BIN_VERSION}-gpu"   python -c 'import tensorflow as tf;print(tf.test.is_gpu_available())'
```

which still gave me False! Hmm. I'll search the error on the internet to see if I can find something useful

**Comment by pgrosu** [comment]
Hi @pichuan,

Try dropping first via a shell like this, and check the LD_LIBRARY_PATH inside the container match with the CUDA libraries location there as would be seen by the applications:

singularity shell --nv -B /usr/lib/locale/:/usr/lib/locale/   docker://google/deepvariant:"${BIN_VERSION}-gpu" 

Paul

**Comment by pichuan** [comment]
I'm going to try out this:

https://stackoverflow.com/questions/67045622/tensorflow-stream-executor-cuda-cuda-driver-cc328-failed-call-to-cuinit-cuda

on the machine where I just installed CUDA 11.3.


First, just `sudo yum install nvidia-modprobe` didn't seem to work for me. So I had this workaround first:

```
sudo su

cat <<EOF > /etc/yum.repos.d/nvidia.repo
[nvidia]
baseurl=https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/
enabled=1
gpgcheck=0
EOF
```

And then
```
sudo yum install nvidia-modprobe
```

Check version:

```
nvidia-modprobe --version
```
shows:
```
nvidia-modprobe:  version 440.118.02
```

check CUDA version again:
```
[pichuan@pichuan-gpu2 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

Try this again:
```
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/   docker://google/deepvariant:"${BIN_VERSION}-gpu"   python -c 'import tensorflow as tf;print(tf.test.is_gpu_available())'
```
Still false -- didn't seem to help:

```
2023-03-16 07:01:52.583106: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-03-16 07:01:52.583190: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: pichuan-gpu2
2023-03-16 07:01:52.583209: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: pichuan-gpu2
2023-03-16 07:01:52.583304: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: INVALID_ARGUMENT: expected %d.%d, %d.%d.%d, or %d.%d.%d.%d form for driver version; got "1"
2023-03-16 07:01:52.583352: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 465.19.1
False
```

I tried one more thing, which is rebooting after installing nvidia-modprobe.

I did:
```
gcloud compute instances reset  --zone us-west1-b pichuan-gpu2
```

and then ssh back to the machine.

```
BIN_VERSION=1.5.0
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/   docker://google/deepvariant:"${BIN_VERSION}-gpu"   python -c 'import tensorflow as tf;print(tf.test.is_gpu_available())'
```

Oh wow, that actually worked. --> it returns True.

Although, now I'm seeing @pgrosu 's comment above, and started wondering if it could be that restarting means I reset $LD_LIBRARY_PATH (because now it's empty , and the command above still worked)

So, my new hypothesis that "nvidia-modprobe helped" might not be true. Need to test with clean setup again :)

But at least something works now! I just don't exactly know what helped yet :)

**Comment by sen1019san** [comment]
Hi, @pichuan . I am trying to run with the followings command:
```
singularity shell -B /usr/lib/locale/:/usr/lib/locale/ --nv ~/data/images/deepvariant_gpu
```
But it still doesn't work.
There are two files in the `/usr/lib/locale/` folder, so I don't know whether it works after rebooting the machine. 
![image](https://user-images.githubusercontent.com/43125963/225547562-bf86b5df-60cd-45d4-8d7c-a6ff986090f4.png)

I will ask the HPC manager to reboot the machine. 
Thanks a lot!

**Comment by pgrosu** [comment]
Hi @sen1019san,

You shouldn't need to reset the machine.  Try to find where the libraries are with the following commands:

```cd /usr```
```find | grep cuda | grep lib```

And this should find it if they are under /usr.  If that does not find them you can try one higher under the root (/) directory or the /lib one.

Paul

**Comment by sen1019san** [comment]
Hi, @pgrosu. Thanks for your reply. 
I find a lot of lib files following your command:
```
cd /usr
find | grep cuda | grep lib
```
Here is the output file.
[find_cude_lib.txt](https://github.com/google/deepvariant/files/10988201/find_cude_lib.txt)

Do you have any suggestion for me to set the variable before starting the deepvariant-gpu singularity program?

**Comment by pbtrial** [comment]
Hi @sen1019san ,

Are you starting a fresh instance everytime? In my experience singularity fails to load all the modules for GPUs to be detected. So you can try this before your singularity command:
`nvidia-modprobe -u -c=0`

This will load all the required modules for singularity to see the GPUs. Otherwise, you can run one of the CUDA samples before running the singularity command. Let me know if this helps.

**Comment by pichuan** [comment]
Great. @sen1019san glad to hear that it works now!
And thanks for @pgrosu and @pbtrial 's help!
